language: cpp

matrix:
  include:
  - os: linux
    dist: xenial
    language: python
    compiler: gcc
    python: "3.7"
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-7
          - g++-7
    env:
      - COMPILER_NAME=gcc-7
      - BUILD_TYPE=Release
      - CONAN_BUILD_TYPE=Release
      - COMPILER_LIBCXX=libstdc++11
      - GTEST_VERSION=1.8.1
      - BOOST_VERSION=1.67.0

  - os: linux
    dist: xenial
    language: python
    compiler: gcc
    python: "3.7"
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-7
          - g++-7
    env:
      - COMPILER_NAME=gcc-7
      - BUILD_TYPE=Debug
      - CONAN_BUILD_TYPE=Debug
      - COMPILER_LIBCXX=libstdc++11
      - GTEST_VERSION=1.8.1
      - BOOST_VERSION=1.67.0

  - os: osx
    osx_image: xcode12.2
    language: cpp
    compiler: clang   
    env:
      - COMPILER_NAME=clang-MacOS
      - BUILD_TYPE=Release
      - CONAN_BUILD_TYPE=Release
      - COMPILER_LIBCXX=libc++
      - GTEST_VERSION=1.8.1
      - BOOST_VERSION=1.67.0

install: 
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 90; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then pip install conan; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew install conan; fi
  - conan user
  - conan remote add systelab-public https://csw.jfrog.io/artifactory/api/conan/cpp-conan-production-local
  - conan --version

script:
  - g++ --version
  - |
    if [ -n "$TRAVIS_TAG" ]; then
      conan export-pkg DbAdapterInterface/conanfile.py "DbAdapterInterface/${TRAVIS_TAG:1}@systelab/stable" -s build_type=${CONAN_BUILD_TYPE} -s compiler.libcxx=${COMPILER_LIBCXX} -o boost=${BOOST_VERSION};
    else
      conan export-pkg DbAdapterInterface/conanfile.py "DbAdapterInterface/0.0.${TRAVIS_BUILD_NUMBER}@systelab/stable" -s build_type=${CONAN_BUILD_TYPE} -s compiler.libcxx=${COMPILER_LIBCXX} -o boost=${BOOST_VERSION};
    fi
  - cd DbAdapterTestUtilities
  - mkdir -p build
  - cd build
  - |
    if [ -n "$TRAVIS_TAG" ]; then
      conan install .. -s build_type=${CONAN_BUILD_TYPE} -s compiler.libcxx=${COMPILER_LIBCXX} -e VERSION="${TRAVIS_TAG:1}" -o gtest=${GTEST_VERSION} -o boost=${BOOST_VERSION};
    else
      conan install .. -s build_type=${CONAN_BUILD_TYPE} -s compiler.libcxx=${COMPILER_LIBCXX} -e VERSION="0.0.${TRAVIS_BUILD_NUMBER}" -o gtest=${GTEST_VERSION} -o boost=${BOOST_VERSION};
    fi
  - cmake .. -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
  - make
  - cd bin
  - if [ $TRAVIS_OS_NAME == osx ]; then cp -f *.dylib /usr/local/lib; fi
  - cd ..
  - |
    if [ -n "$TRAVIS_TAG" ]; then
      conan export-pkg ../conanfile.py "DbAdapterTestUtilities/${TRAVIS_TAG:1}@systelab/stable" -s build_type=${CONAN_BUILD_TYPE} -s compiler.libcxx=${COMPILER_LIBCXX} -o gtest=${GTEST_VERSION} -o boost=${BOOST_VERSION};
    else
      conan export-pkg ../conanfile.py "DbAdapterTestUtilities/0.0.${TRAVIS_BUILD_NUMBER}@systelab/stable" -s build_type=${CONAN_BUILD_TYPE} -s compiler.libcxx=${COMPILER_LIBCXX} -o gtest=${GTEST_VERSION} -o boost=${BOOST_VERSION};
    fi
  - |
    if [ "$BUILD_TYPE" == "Release" ] || [ "$BUILD_TYPE" == "Debug" ]; then
      if [ -n "$TRAVIS_TAG" ]; then
        conan test ../test_package/conanfile.py DbAdapterTestUtilities/${TRAVIS_TAG:1}@systelab/stable -s build_type=${CONAN_BUILD_TYPE} -s compiler.libcxx=${COMPILER_LIBCXX} -o gtest=${GTEST_VERSION} -o boost=${BOOST_VERSION};
      else
        conan test ../test_package/conanfile.py DbAdapterTestUtilities/0.0.${TRAVIS_BUILD_NUMBER}@systelab/stable -s build_type=${CONAN_BUILD_TYPE} -s compiler.libcxx=${COMPILER_LIBCXX} -o gtest=${GTEST_VERSION} -o boost=${BOOST_VERSION};
      fi
    fi
  - cd ..
  - cd ..

deploy:
  - provider: script
    skip_cleanup: true
    script: bash ./ci/deploy.sh -v "${TRAVIS_TAG:1}"
    on:
      tags: true
  - provider: script
    script: bash ./ci/build_docs.sh -o "systelab" -s "cpp-db-adapter" -t "${TRAVIS_TAG}" -c "Travis" -n "${COMPILER_NAME} ${BUILD_TYPE}" -j "${TRAVIS_JOB_ID}"
    skip_cleanup: true
    on:
      tags: true
