language: cpp

matrix:
  include:
  - os: linux
    dist: xenial
    compiler: gcc
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-7
          - g++-7
    env:
      - BUILD_TYPE=Release
      - CONAN_BUILD_TYPE=Release
      - COMPILER_LIBCXX=libstdc++11

  - os: linux
    dist: xenial
    compiler: gcc
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-7
          - g++-7
    env:
      - BUILD_TYPE=Debug
      - CONAN_BUILD_TYPE=Debug
      - COMPILER_LIBCXX=libstdc++11

  - os: osx
    osx_image: xcode10.1
    compiler: clang   
    env:
      - BUILD_TYPE=Release
      - CONAN_BUILD_TYPE=Release
      - COMPILER_LIBCXX=libc++

install: 
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 90; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then pip install conan --user; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew install conan; fi
  - conan user
  - conan remote add systelab-bintray https://api.bintray.com/conan/systelab/conan
  - conan --version

script:
  - g++ --version
  - |
    if [ -n "$TRAVIS_TAG" ]; then
      conan export-pkg DbAdapterInterface/conanfile.py "DbAdapterInterface/${TRAVIS_TAG:1}@systelab/stable" -s build_type=${CONAN_BUILD_TYPE} -s compiler.libcxx=${COMPILER_LIBCXX};
    else
      conan export-pkg DbAdapterInterface/conanfile.py "DbAdapterInterface/0.0.${TRAVIS_BUILD_NUMBER}@systelab/stable" -s build_type=${CONAN_BUILD_TYPE} -s compiler.libcxx=${COMPILER_LIBCXX};
    fi
  - mkdir -p build
  - cd build
  - |
    if [ -n "$TRAVIS_TAG" ]; then
      conan install ../DbAdapterTestUtilities -s build_type=${CONAN_BUILD_TYPE} -s compiler.libcxx=${COMPILER_LIBCXX} -e VERSION="${TRAVIS_TAG:1}";
    else
      conan install ../DbAdapterTestUtilities -s build_type=${CONAN_BUILD_TYPE} -s compiler.libcxx=${COMPILER_LIBCXX} -e VERSION="0.0.${TRAVIS_BUILD_NUMBER}";
    fi
  - cmake .. -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
  - make
  - cd bin
  - if [ $TRAVIS_OS_NAME == osx ]; then cp -f *.dylib /usr/local/lib; fi
  - cd ..
  - |
    if [ -n "$TRAVIS_TAG" ]; then
      conan export-pkg ../DbAdapterTestUtilities/conanfile.py "DbAdapterTestUtilities/${TRAVIS_TAG:1}@systelab/stable" -s build_type=${CONAN_BUILD_TYPE} -s compiler.libcxx=${COMPILER_LIBCXX};
    else
      conan export-pkg ../DbAdapterTestUtilities/conanfile.py "DbAdapterTestUtilities/0.0.${TRAVIS_BUILD_NUMBER}@systelab/stable" -s build_type=${CONAN_BUILD_TYPE} -s compiler.libcxx=${COMPILER_LIBCXX};
    fi
  - |
    if [ "$BUILD_TYPE" == "Release" ] || [ "$BUILD_TYPE" == "Debug" ]; then
      if [ -n "$TRAVIS_TAG" ]; then
        conan test ../test_package/conanfile.py DbAdapterTestUtilities/${TRAVIS_TAG:1}@systelab/stable -s build_type=${CONAN_BUILD_TYPE} -s compiler.libcxx=${COMPILER_LIBCXX};
      else
        conan test ../test_package/conanfile.py DbAdapterTestUtilities/0.0.${TRAVIS_BUILD_NUMBER}@systelab/stable -s build_type=${CONAN_BUILD_TYPE} -s compiler.libcxx=${COMPILER_LIBCXX};
      fi
    fi
  - cd ..

deploy:
  provider: script
  skip_cleanup: true
  script: bash ./deploy.sh -v "${TRAVIS_TAG:1}"
  on:
    tags: true
